'use strict';
const D=window.TRAINING_DATA;
const esc=v=>String(v??'Desconegut').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=d=>d.split('-').reverse().join('/');
const number=n=>n==null?'—':Number(n).toLocaleString('ca-ES',{maximumFractionDigits:2});
const duration=n=>n==null?'—':Math.floor(n)+':'+String(Math.round(n*60)%60).padStart(2,'0');
const type=t=>t==='Gym'?'Força':t;
const sessions=[...D.sessions].sort((a,b)=>b.date.localeCompare(a.date));
const metric=(label,value)=>`<div><div class="k">${esc(label)}</div><div class="v">${esc(value)}</div></div>`;
function row(s){return `<details class="session"><summary><span class="date">${date(s.date)}</span> <span class="name">${esc(s.name)}</span> <span class="tag">${type(s.type)}</span><div class="meta">${number(s.distance_km)} km · ${duration(s.duration_min)} min · FC ${number(s.avg_hr)}/${number(s.max_hr)}</div></summary><div class="detail"><dl>${Object.entries(s).map(([k,v])=>`<div><dt>${esc(labels[k]||k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></div></details>`;}
const labels={date:'Data',type:'Activitat',name:'Entrenament',duration_min:'Durada (min)',distance_km:'Distància (km)',avg_hr:'FC mitjana (ppm)',max_hr:'FC màxima (ppm)',avg_cadence:'Cadència mitjana',max_cadence:'Cadència màxima',avg_power_w:'Potència mitjana (W)',max_power_w:'Potència màxima (W)',notes:'Notes i sensacions',summary:'Resum',training_effect_aerobic:'Training Effect aeròbic',training_effect_anaerobic:'Training Effect anaeròbic',calories_active:'Calories actives',calories_total:'Calories totals',hub_notes:'Notes Training Hub',hub_summary:'Resum Training Hub',hub_name:'Nom Training Hub',z1_min:'Z1 (min)',z2_min:'Z2 (min)',z3_min:'Z3 (min)',z4_min:'Z4 (min)',z5_min:'Z5 (min)'};
let filter='ALL';
function render(){const y=document.querySelector('#year').value,m=document.querySelector('#month').value,q=document.querySelector('#search').value.toLocaleLowerCase();const found=sessions.filter(s=>(filter==='ALL'||s.type===filter)&&(!y||s.date.startsWith(y))&&(!m||s.date.slice(5,7)===m)&&(!q||(s.name+' '+(s.notes||'')).toLocaleLowerCase().includes(q)));document.querySelector('#sessions').innerHTML=found.map(row).join('')||'<p>No hi ha sessions amb aquests filtres.</p>';document.querySelector('#count').textContent=found.length+' de '+sessions.length+' sessions';}
const years=[...new Set(sessions.map(s=>s.date.slice(0,4)))].sort().reverse();document.querySelector('#year').innerHTML='<option value="">Tots els anys</option>'+years.map(y=>`<option>${y}</option>`).join('');
for(const id of ['year','month','search'])document.getElementById(id).addEventListener('input',render);
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render();});
document.querySelector('#recent').innerHTML=sessions.slice(0,3).map(row).join('');
const latest=sessions[0];document.querySelector('#resum .grid').children[2].innerHTML=metric('Última sessió',date(latest.date))+`<div class="small">${esc(latest.name)}</div>`;
document.querySelector('.progress').remove();
function table(rows,fields){return `<div class="table-scroll"><table><thead><tr>${fields.map(([k,l])=>`<th>${esc(l)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${fields.map(([k])=>`<td>${esc(r[k]??'—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
document.querySelector('#pes').innerHTML=`<div class="card"><h2>Pes · ${D.weights.length} registres</h2>${table([...D.weights].sort((a,b)=>b.date.localeCompare(a.date)),[['date','Data'],['kg','Pes (kg)']])}</div><div class="card"><h2>Composició corporal · ${D.inbody.length} registres</h2><p class="small">Valors originals preservats. Puntuacions 0 de la font es mostren com a desconegudes.</p>${table([...D.inbody].sort((a,b)=>b.date.localeCompare(a.date)).map(r=>({...r,score:r.score||'—'})),[['date','Data'],['weight','Pes (kg)'],['fat_pct','Greix (%)'],['fat_mass','Greix (kg)'],['muscle','Múscul (kg)'],['bmi','IMC'],['visceral','Greix visceral'],['score','Puntuació']])}</div>`;
const totals={};for(const s of sessions.filter(s=>s.type==='Running')){const key=s.date.slice(0,7);totals[key]=(totals[key]||0)+(s.distance_km||0);}
document.querySelector('#evolucio').innerHTML=`<div class="card"><h2>Històric migrat</h2><div class="grid">${metric('Sessions',sessions.length)}${metric('Resums mensuals',D.monthly.length)}${metric('Pesatges',D.weights.length)}${metric('Curses',D.races.length)}</div></div><div class="card"><h2>Quilometratge mensual · Running</h2><p class="small">Calculat amb les sessions individuals disponibles; no representa necessàriament tot el volum d’anys anteriors.</p>${table(Object.entries(totals).sort((a,b)=>b[0].localeCompare(a[0])).map(([month,km])=>({month,km:number(km)})),[['month','Mes'],['km','km registrats']])}</div><div class="card"><h2>Resums mensuals originals</h2>${table([...D.monthly].reverse(),[['month','Mes'],['vigorous_min','Min vigorosos'],['moderate_min','Min moderats'],['max_hr','FC màx.'],['avg_resting_hr','FC repòs'],['gym_sessions','Sessions gimnàs'],['gym_calories','Calories gimnàs'],['gym_duration_min','Min gimnàs']])}</div>`;
document.querySelector('#curses').innerHTML=`<div class="card"><h2>Curses · ${D.races.length} registres</h2>${table([...D.races].sort((a,b)=>b.data.localeCompare(a.data)),[['data','Data'],['lloc','Cursa'],['tc','Distància'],['tempsReal','Temps real'],['temps','Temps oficial'],['mitja','Ritme'],['posicio','Posició'],['posCat','Pos. categoria'],['dorsal','Dorsal'],['obs','Sensacions']])}</div>`;
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===b.dataset.page));});
render();
